name: PlugPact Build Engine

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Stable Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          # FORCING GRADLE 8.5 FOR MAXIMUM STABILITY
          gradle-version: 8.5

      - name: Build PlugPact APK
        run: gradle assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: PlugPact-v1-Debug
          path: app/build/outputs/apk/debug/*.apk
